---
- name: Converge
  hosts: all
  vars:
    acme_certificate_directory: https://acme-staging.api.letsencrypt.org/directory
    acme_certificate_email: ci@nephelai.io
    acme_certificate_domain: "{{ ansible_hostname }}.nephelai.io"
    acme_certificate_aws_accesskey_id: "{{ lookup('env', 'AWS_AK_ID') }}"
    acme_certificate_aws_accesskey_secret: "{{ lookup('env', 'AWS_AK_SECRET') }}"
  roles:
    - role: acme-dnschallenge-route53
